### ISSUE TITLE
postcss plugins

### ISSUE THREAD

**Issue by calderaro** [grvcoelho/wildfire#5]
This boilerplate is very nice just what i need thanks you. The only extra thing i need is to add some postcss plugins like autoprefixer and precss but i can not make it work with webpack 2 and can not find documentation ¿do you know how to make it work?

**Comment by TuckerWhitehouse** [comment]
https://github.com/postcss/postcss-loader uses the https://github.com/michael-ciniawsky/postcss-load-config package, which allows you to specify your configuration / plugins in a variety of different ways including a `postcss.config.js` file.

**Comment by calderaro** [comment]
that's amazing thanks you!

**Comment by grvcoelho** [comment]
Hey @calderaro, I've created a PR showing how to use postcss plugins from inside webpackfile :smile:

There are some issues with the postcss loader loading plugins, so the solution atm, is to use `webpack.LoadOptionsPlugin` to get around this :tada:
